/**
 * Records the golden corpus: `npm run goldens`.
 *
 * 25 self-play games under the v0 rules, each stored as its record -- the only
 * thing that needs storing, since `{ setup, actions }` replays die for die -- plus
 * a digest of the final state it produced. `golden.test.ts` replays them and
 * compares. A phase that changes no outcome leaves this file untouched; a phase
 * that changes one has to say so in the diff.
 *
 * **Regenerating this file is the one move that can hide a bug**, so a commit that
 * does it explains why. It is not a snapshot to be refreshed when it goes red.
 *
 * Which 25 games: the first seeds that reach an ending inside `MAX_DECISIONS`.
 * Random self-play usually does not -- about two thirds of seeds are still going at
 * 800 decisions and the median winner takes 1100 -- and taking seeds 1-25 as they
 * come produced a corpus that was two thirds unfinished games and six megabytes.
 * Selecting for endings buys both things that were missing: every game exercises
 * capture, the win check and `game_over`, and the file stays small enough that its
 * diff can be read. Breadth is not this file's job -- the 1000-game fuzz does that,
 * unselected, every run.
 */
import { writeFileSync } from 'node:fs'

import { randomAi } from '../ai/random'
import { runGame } from '../ai/run'
import { digestState, type StateDigest } from '../engine/digest'
import type { GameRecord } from '../engine/replay'
import { STARTER_FORCES, type SetupOptions } from '../engine/setup'

const GAMES = 25
const MAX_DECISIONS = 800
/** Give up rather than scan forever if a rules change makes short games rare. */
const MAX_SEED = 1000

const OUT = new URL('../engine/__golden__/v0-games.json', import.meta.url)

export interface GoldenGame {
  readonly seed: number
  readonly aiSeed: number
  readonly decisions: number
  readonly stoppedBecause: 'winner' | 'stuck' | 'cap'
  readonly record: GameRecord
  readonly digest: StateDigest
}

function play(seed: number): GoldenGame {
  const setup: SetupOptions = {
    seed,
    forces: STARTER_FORCES,
  }
  const aiSeed = seed * 7
  const result = runGame({
    setup,
    players: { p1: randomAi, p2: randomAi },
    aiSeed,
    maxDecisions: MAX_DECISIONS,
  })

  if (result.stoppedBecause === 'stuck') {
    throw new Error(`seed ${seed} ran out of moves without ending -- that is a bug, not a golden`)
  }

  return {
    seed,
    aiSeed,
    decisions: result.decisions,
    stoppedBecause: result.stoppedBecause,
    record: result.record,
    digest: digestState(result.state),
  }
}

function main(): void {
  const games: GoldenGame[] = []
  let seed = 0

  while (games.length < GAMES) {
    seed += 1
    if (seed > MAX_SEED) {
      throw new Error(
        `scanned ${MAX_SEED} seeds and found only ${games.length} games ending inside ` +
          `${MAX_DECISIONS} decisions; raise the cap, or find out why games got longer`,
      )
    }
    const game = play(seed)
    if (game.stoppedBecause === 'winner') games.push(game)
  }

  // Hand-assembled rather than `JSON.stringify(corpus, null, 2)`: one game per
  // line means a diff names the games that moved, which is the whole question you
  // ask of this file. Minified it would be one unreadable line; pretty-printed it
  // would be a hundred thousand.
  const body = games.map((game) => JSON.stringify(game)).join(',\n')
  const text =
    '{\n' +
    `"_comment": "Generated by npm run goldens. Do not hand-edit. Regenerating is the one move that can hide a bug -- see docs/PLAN-V1.md, Phase G.",\n` +
    `"version": 1,\n` +
    `"games": [\n${body}\n]\n}\n`

  writeFileSync(OUT, text)

  const decisions = games.reduce((sum, g) => sum + g.decisions, 0)
  console.log(
    `wrote ${games.length} decided games from seeds 1-${seed}, ` +
      `${decisions} decisions, ${(text.length / 1024).toFixed(0)} KB`,
  )
}

main()
