/**
 * The magic pool: what a caster has to spend, and what they may spend it on.
 *
 * **Magic per species, not one number** (v2 Phase 1). Two rules on p. 13 meet here:
 * each unit's magic results "may be divided between that unit's elements", and "a
 * species spell may only be cast with results generated by units from that species".
 * So a pool is a list of *suppliers* -- one per species whose dice generated magic,
 * each splittable freely between that species' elements -- and paying for an
 * announcement is a small transport problem: suppliers offer points, spells demand
 * them by element and, for a species spell, by species. `allocationProblem` solves it
 * exactly, by Hall's condition over the suppliers (at most a handful).
 *
 * **A single-species force keeps v1's pool exactly**: one number, split freely
 * between the species' two elements, with `suppliers` omitted. v1 leaned on that
 * ("the whole army's magic is a single total"), `turn.magic.pool` and the
 * `announce_spells` pending sit inside the golden digest, and a one-supplier transport
 * problem *is* a sum -- so the list appears only when the caster's force holds more
 * than one species, and never otherwise.
 *
 * `resolveFaces` stays pure and `GameState`-free: the per-species split is read off
 * the dice it already returns (`magicBySpecies`), since a `DieRoll` names its type.
 *
 * **House rule** (`RULES-V0.md` section 15): an army modifier on a magic roll -- Ash
 * Storm's minus one is the only one today -- is taken from whichever species' results
 * the caster likes. That is what "the pool total is below the sum of its suppliers"
 * means: suppliers carry what their dice rolled, and the total caps the spend. Results
 * that no die generated would be a supplier of no species, paying only for a spell
 * any species may cast; no modifier in the game adds magic, so that is a statement.
 */
import { SPECIES, speciesElements, terrainDie, terrainType, unitType } from '../data/load'
import {
  spell,
  spellAcceptsElement,
  spellAllowsSpecies,
  SPELLS,
  type Spell,
} from '../data/spells'
import type { Element } from '../data/types'

import { iconAt, resolvesIcon, shielded } from './effects'
import { resolvesSpell, summonable } from './spells'
import {
  army as armyOf,
  armyRefOf,
  deadUnits,
  forceSpecies,
  livingUnits,
  opponentOf,
  speciesIn,
  TERRAIN_SLOTS,
  type AnnouncedSpell,
  type ArmyRef,
  type GameState,
  type PlayerId,
  type RuleSet,
  type SpellTarget,
  type UnitId,
} from './types'

/**
 * Magic results a caster may spend, and the two permissions that narrow what they buy.
 *
 * Both restrictions are `?: true` and omitted rather than `false`: this lands on
 * `turn.magic.pool` and therefore inside `digestState`'s `stableJson(state.turn)`.
 */
export interface MagicPool {
  /** What the roll came to: the most the announcement may spend in all. */
  readonly points: number
  /** Which elements these points may be spent as: the caster's species' elements,
   *  widened by a Standing Stones the casting army holds. Every supplier's, for a
   *  mixed force. */
  readonly elements: readonly Element[]
  /**
   * Who generated the points, per species (v2 Phase 1). **Present only when the
   * caster's force holds more than one species** -- omitted otherwise, near the digest,
   * and then the pool is one supplier of `points` in `elements`. See the file comment.
   */
  readonly suppliers?: readonly MagicSupplier[]
  /** Cantrip's second sentence: these points buy only `C`-marked spells. */
  readonly cantripOnly?: true
  /** Cast from the Reserve Area: only `R`-marked spells. */
  readonly fromReserves?: true
}

/**
 * One species' share of a pool: the magic its dice rolled, and the elements it may be
 * spent as -- the species' own, widened by a Standing Stones like everyone's.
 */
export interface MagicSupplier {
  /** Whose dice generated these points; null for points no die generated, which pay
   *  only for a spell any species may cast. */
  readonly species: string | null
  readonly points: number
  readonly elements: readonly Element[]
}

/** The magic each species' dice contributed to a roll, read off the dice alone. */
export function magicBySpecies(
  dice: readonly { readonly typeId: string; readonly results: number }[],
): Readonly<Record<string, number>> {
  const out: Record<string, number> = {}
  for (const die of dice) {
    if (die.results <= 0) continue
    const species = unitType(die.typeId).species
    out[species] = (out[species] ?? 0) + die.results
  }
  return out
}

/**
 * The elements an army's magic may be spent as.
 *
 * Standing Stones -- "all units in your controlling army may convert any or all of
 * their magic results to an element this terrain contains" -- is the only thing that
 * widens it, and it comes live for free: `iconAt` returns null unless
 * `eighthFace: 'full'`, and `resolvesIcon` already gates the icon itself on
 * `magic: 'spells'`.
 */
export function castingElements(
  state: GameState,
  player: PlayerId,
  ref: ArmyRef,
  /** Whose elements: one supplier's species, or by default the whole force's. */
  species: readonly string[] = forceSpecies(state, player),
): readonly Element[] {
  const own: Element[] = []
  for (const id of species) for (const e of speciesElements(id)) if (!own.includes(e)) own.push(e)
  if (ref === 'reserve') return own
  if (iconAt(state, player, ref) !== 'standing_stones') return own
  // `iconAt` answers "is that icon showing and mine", which is not the same question
  // as "does it do anything in the rules being played". Standing Stones is gated on
  // `magic: 'spells'` rather than on the eighth-face rung -- converting magic results
  // to an element is meaningless until results have elements -- so this has to ask
  // `resolvesIcon` too. Nothing reads the answer under the v0 house rule, which is
  // exactly why it would have stayed wrong.
  if (!resolvesIcon('standing_stones', state.ruleSet)) return own

  const here = terrainType(terrainDie(state.terrains[ref].dieId).type).elements
  return [...own, ...here.filter((e) => !own.includes(e))]
}

/**
 * The ordinary pool for a magic action.
 *
 * `bySpecies` is what each species' dice rolled (`magicBySpecies`), and it is read only
 * for a mixed force: a single-species force's pool is one number, as it always was.
 */
export function magicPool(
  state: GameState,
  player: PlayerId,
  ref: ArmyRef,
  points: number,
  bySpecies: Readonly<Record<string, number>> = {},
): MagicPool {
  const reserve = ref === 'reserve' ? { fromReserves: true as const } : {}
  if (forceSpecies(state, player).length <= 1) {
    return { points, elements: castingElements(state, player, ref), ...reserve }
  }

  const suppliers: MagicSupplier[] = Object.entries(bySpecies)
    .filter(([, n]) => n > 0)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([species, n]) => ({ species, points: n, elements: castingElements(state, player, ref, [species]) }))
  const attributed = suppliers.reduce((sum, s) => sum + s.points, 0)
  if (points > attributed) {
    const here = speciesIn(armyOf(state, player, ref))
    suppliers.push({
      species: null,
      points: points - attributed,
      elements: castingElements(state, player, ref, here.length > 0 ? here : undefined),
    })
  }

  const elements: Element[] = []
  for (const s of suppliers) for (const e of s.elements) if (!elements.includes(e)) elements.push(e)
  return { points, elements, suppliers, ...reserve }
}

/**
 * Cantrip's restricted pool, from a non-magic non-maneuver roll.
 *
 * Its points are the Cantrip faces the caster rolled, which may be on dice of two
 * species in a mixed army; the task that carries them has summed them, so the split is
 * read back off the dice parked on the exchange.
 */
export function cantripPool(
  state: GameState,
  player: PlayerId,
  ref: ArmyRef,
  points: number,
): MagicPool {
  return { ...magicPool(state, player, ref, points, cantripBySpecies(state, player)), cantripOnly: true }
}

/** The Cantrip faces a player rolled in the exchange on the table, by species. */
function cantripBySpecies(state: GameState, player: PlayerId): Readonly<Record<string, number>> {
  const combat = state.turn.combat
  const dice = [...(combat?.attack?.dice ?? []), ...(combat?.saves?.dice ?? [])]
  const out: Record<string, number> = {}
  for (const die of dice) {
    if (state.units[die.unitId]?.owner !== player) continue
    const face = unitType(die.typeId).faces[die.faceIndex]
    if (face?.icon !== 'SAI' || face.sai !== CANTRIP) continue
    const species = unitType(die.typeId).species
    out[species] = (out[species] ?? 0) + face.count
  }
  return out
}

const CANTRIP = 'Cantrip'

/** One supplier as the allocation sees it: what it has, and which spells it may pay. */
interface Payer {
  readonly label: string
  readonly points: number
  readonly elements: readonly Element[]
  readonly pays: (spellSpecies: string) => boolean
}

const speciesName = (id: string): string => SPECIES.find((s) => s.id === id)?.name ?? id

/**
 * The pool's suppliers. A single-species pool is one supplier that pays for anything
 * offered: which species spells it may cast was settled by `castableSpells`, against
 * the force's one species, before anything reached an announcement.
 */
function payers(pool: MagicPool): readonly Payer[] {
  if (pool.suppliers === undefined) {
    return [{ label: 'the', points: pool.points, elements: pool.elements, pays: () => true }]
  }
  return pool.suppliers.map((s) => ({
    label: s.species === null ? 'the unattributed' : `the ${speciesName(s.species)}`,
    points: s.points,
    elements: s.elements,
    pays: (spellSpecies: string) =>
      spellSpecies === 'any' || (s.species !== null && spellSpecies === s.species),
  }))
}

/** One spell's claim on a pool: so many points, of this element, for this species. */
interface Demand {
  readonly species: string
  readonly element: Element
  readonly points: number
}

const demandOf = (cast: {
  readonly spell: string
  readonly element: Element
  readonly count: number
}): Demand => {
  const s = spell(cast.spell)
  return { species: s.species, element: cast.element, points: s.cost * cast.count }
}

/**
 * Why no split of the pool pays for these demands, or null.
 *
 * Hall's condition, which is exact for a transport problem: for every set `U` of
 * suppliers, the demands that *only* suppliers in `U` can pay must fit in what `U`
 * holds. A pool has one supplier per species (and at most one of no species), so the
 * subsets are few. The total is checked separately, by the caller: the suppliers carry
 * what their dice rolled, and an army modifier may have left the pool smaller.
 */
function allocationProblem(pool: MagicPool, demands: readonly Demand[]): string | null {
  const ps = payers(pool)
  const can = demands.map((d) => ps.map((p) => p.pays(d.species) && p.elements.includes(d.element)))

  for (let mask = 0; mask < 1 << ps.length; mask++) {
    const inside = (i: number) => (mask & (1 << i)) !== 0
    const supply = ps.reduce((sum, p, i) => sum + (inside(i) ? p.points : 0), 0)
    const need = demands.reduce(
      (sum, d, j) => sum + ((can[j] ?? []).every((ok, i) => !ok || inside(i)) ? d.points : 0),
      0,
    )
    if (need <= supply) continue
    const who = ps.filter((_, i) => inside(i)).map((p) => `${p.label} magic`)
    return who.length === 0
      ? 'nothing in the pool can pay for one of these spells in the element announced'
      : `these spells need ${need} magic that only ${who.join(' and ')} can pay, and ${supply} was rolled`
  }
  return null
}

/** One spell this pool could buy, and how. */
export interface Castable {
  readonly spell: Spell
  /** The pool's elements this spell accepts: its own, or all of them if Elemental. */
  readonly elements: readonly Element[]
  /** How many combined castings the pool could afford. 1 for a non-cumulative spell,
   *  which gains nothing from a second casting on the same target. */
  readonly maxCount: number
  /** Every legal target, so the client offers a list rather than computing one and
   *  the engine validates against exactly what it offered. */
  readonly targets: readonly SpellTargetOffer[]
}

/**
 * One target, and the fewest castings that can reach it.
 *
 * `minCount` exists because Resurrect Dead's cost is a property of what it is aimed
 * at: "target one health-worth of units in your DUA", multiplied by the castings, so a
 * 2-health unit needs two castings and six magic. Carrying it on the offer is what
 * keeps the rule in one place -- a client that shows a target the engine will then
 * refuse is the bug this whole shape exists to prevent, and the fuzz found it within
 * a hundred games.
 *
 * 1 for every other spell, where a target is a target and the count is free.
 *
 * `elements` is the same idea for colour (v2 Phase 2): the elements a casting at this
 * target may be paid in, **present only when narrower** than the castable's own list.
 * Resurrect Dead raises only a die whose species "contains the element of magic used",
 * and a mixed force's DUA holds dice of two colours, so a Firewalker in it takes air
 * or fire and not the water the same casting could otherwise be paid in. A single-species
 * DUA never narrows anything, which keeps the field out of every recorded game. Read it
 * through `elementsFor`.
 */
/** Scent of Fear's "up to three health-worth", per casting. */
const SCENT_OF_FEAR_HEALTH = 3

export interface SpellTargetOffer {
  readonly target: SpellTarget
  readonly minCount: number
  readonly elements?: readonly Element[]
}

/** The elements a casting of `castable` at `target` may be paid in -- the one rule every
 *  client applies before it asks which element, so none offers a colour the engine then
 *  refuses (`spellTargetProblem`). */
export function elementsFor(castable: Castable, target: SpellTarget): readonly Element[] {
  const offer = castable.targets.find((t) => sameSpellTarget(t.target, target))
  return offer?.elements ?? castable.elements
}

/** `elementsFor` the other way round, for a client that asks the element first: the
 *  targets a casting paid in `element` may be aimed at. */
export function targetsFor(castable: Castable, element: Element): readonly SpellTargetOffer[] {
  return castable.targets.filter((t) => t.elements === undefined || t.elements.includes(element))
}

/**
 * Every target this spell could legally be aimed at right now.
 *
 * "The target of a spell, or the conditions for a spell's effect to occur, must exist
 * at the time the target is selected" (p. 13) -- so an empty army is not a target, and
 * a spell with no target at all is not offered.
 *
 * A Reserve Army is an army: "target any army" names it, and Wind Walk on a Reserve
 * Army is legal and useless, which is the player's business rather than the engine's.
 */
export function spellTargets(
  state: GameState,
  caster: PlayerId,
  s: Spell,
): readonly SpellTargetOffer[] {
  // The opponent's army, and every die in it, when `shielded` says so: at a Temple it
  // holds, against death magic (v2 Phase 7e), and under an Illusion, against any spell
  // (8b). A terrain stays a target -- Soiled Ground's check skips the holder's dice
  // itself -- and so does a die in no army, which no shield stands over.
  const from = s.element === 'death' ? 'death_spell' : 'spell'
  return targetOffers(state, caster, s).filter((offer) => {
    const target = offer.target
    if (target.kind === 'army') return !shielded(state, caster, target.player, target.army, from)
    if (target.kind === 'units') {
      return target.unitIds.every((id) => {
        const unit = state.units[id]
        const ref = unit === undefined ? null : armyRefOf(state, id)
        return unit === undefined || ref === null || !shielded(state, caster, unit.owner, ref, from)
      })
    }
    return true
  })
}

function targetOffers(state: GameState, caster: PlayerId, s: Spell): readonly SpellTargetOffer[] {
  const once = (target: SpellTarget): SpellTargetOffer => ({ target, minCount: 1 })

  const armies = (player: PlayerId): SpellTargetOffer[] =>
    ([...TERRAIN_SLOTS, 'reserve'] as readonly ArmyRef[])
      .filter((ref) => armyOf(state, player, ref).length > 0)
      .map((ref) => once({ kind: 'army', player, army: ref }))

  switch (s.target) {
    case 'army':
      return [...armies(caster), ...armies(opponentOf(caster))]
    // The house rule (v1 Phase 9a): a beneficial army spell reaches only your own.
    case 'own_army':
      return armies(caster)
    case 'opposing_army':
      return armies(opponentOf(caster))
    case 'terrain':
      return TERRAIN_SLOTS
        // Wall of Thorns: "target any terrain not at its eighth face". Offered there
        // until Phase 9a, because the target list was every terrain for every spell.
        .filter((slot) => s.id !== 'wall_of_thorns' || state.terrains[slot].face !== 8)
        .map((slot) => once({ kind: 'terrain', slot }))

    // Accelerated Growth: "target your DUA" -- the area, not a unit in it, so one
    // target at one casting. Offered **whatever the DUA holds**: the effect lasts until
    // your next turn, and a DUA empty now fills with the first 1-health die that dies,
    // which is exactly when the effect is waiting to be used. The area always exists,
    // and that is all p. 13 asks of a target. (Phase 9a first shipped this requiring a
    // dead die, carried over from the per-unit offers it replaced.)
    case 'dua':
      return [once({ kind: 'dua', player: caster })]

    // Path. One unit per target rather than a set: the rules let a cumulative spell be
    // "cast multiple separate times, with a different target each time", which is how
    // a caster moves two units, and a set would need a budgeted selection at
    // announcement for no gain.
    case 'own_unit':
      return TERRAIN_SLOTS.flatMap((slot) =>
        armyOf(state, caster, slot).map((unit) => once({ kind: 'units', unitIds: [unit.id] })),
      )

    // Resurrect Dead. A unit's health *is* the number of castings it needs, so the
    // offer carries it and neither client has to know the rule.
    case 'own_dua':
      return deadUnits(state, caster).map((unit) => ({
        target: { kind: 'units', unitIds: [unit.id] } as const,
        minCount: unitType(unit.typeId).health,
      }))

    // Lightning Strike: "target any opposing unit". Reserves included -- the rules
    // shield a Reserve Army from missile fire and from dragons, and say nothing about
    // magic.
    //
    // Finger of Death (v2 Phase 7e): one point per casting and no save, so fewer
    // castings than the die's health do nothing at all -- the price rides on the offer,
    // Resurrect Dead's way.
    case 'opposing_unit':
      return livingUnits(state, opponentOf(caster)).map((unit) =>
        s.handler === 'finger_of_death'
          ? { target: { kind: 'units', unitIds: [unit.id] } as const, minCount: unitType(unit.typeId).health }
          : once({ kind: 'units', unitIds: [unit.id] }),
      )

    // Scent of Fear (v2 Phase 7e): "up to three health-worth of opposing units at any
    // terrain", Mirage's reading and Mirage's one unit per casting (RULES-V0.md section
    // 19) -- so three health a casting, and a monster needs two.
    case 'opposing_units':
      return TERRAIN_SLOTS.flatMap((slot) =>
        armyOf(state, opponentOf(caster), slot).map((unit) => ({
          target: { kind: 'units', unitIds: [unit.id] } as const,
          minCount: Math.ceil(unitType(unit.typeId).health / SCENT_OF_FEAR_HEALTH),
        })),
      )

    // Mirage: "up to five health-worth of units **at any terrain**" -- so not
    // Reserves, and either player's. One unit per casting; see RULES-V0.md section 15.
    case 'units':
      return TERRAIN_SLOTS.flatMap((slot) =>
        [caster, opponentOf(caster)].flatMap((player) =>
          armyOf(state, player, slot).map((unit) => once({ kind: 'units', unitIds: [unit.id] })),
        ),
      )
  }
}

/**
 * Whether this announced cast is magic that a Dispel Magic on `unitId` would stop.
 *
 * "Negate all unresolved magic that targets **or effects** this unit, its army or the
 * terrain it occupies." One predicate, in the engine, because three things ask it --
 * who is even offered the roll, what the prompt lists, and what the answer negates --
 * and three copies of "does this spell reach me" is how two of them start disagreeing.
 *
 * Note what it does *not* care about: whose spell it is. A Unicorn stops its own side's
 * magic as readily as the enemy's, which is the rule as written.
 */
export function dispelNegates(state: GameState, cast: AnnouncedSpell, unitId: UnitId): boolean {
  if (cast.negated === true) return false
  const unit = state.units[unitId]
  if (unit === undefined) return false

  switch (cast.target.kind) {
    case 'none':
      return false
    // A DUA is not a unit, its army or the terrain it occupies.
    case 'dua':
      return false
    case 'units':
      return cast.target.unitIds.includes(unitId)
    case 'army':
      return (
        cast.target.player === unit.owner &&
        cast.target.army ===
          (unit.location.kind === 'terrain' ? unit.location.slot : 'reserve')
      )
    case 'terrain':
      return unit.location.kind === 'terrain' && unit.location.slot === cast.target.slot
  }
}

/** Every die that could dispel something in this announcement, in board order. */
export function dispelCandidates(
  state: GameState,
  casts: readonly AnnouncedSpell[],
): readonly UnitId[] {
  return Object.values(state.units)
    .filter((unit) => unit.location.kind === 'terrain' || unit.location.kind === 'reserve')
    .filter((unit) =>
      unitType(unit.typeId).faces.some(
        (face) => face.icon === 'SAI' && face.sai === DISPEL_MAGIC,
      ),
    )
    .filter((unit) => casts.some((cast) => dispelNegates(state, cast, unit.id)))
    .map((unit) => unit.id)
}

export const DISPEL_MAGIC = 'Dispel Magic'

/**
 * Why this whole announcement is illegal, or null.
 *
 * Separate from `spellTargetProblem` because it is a rule *between* casts rather than
 * about any one of them -- and it is the rule that proves an announcement has to be
 * validated as a whole rather than cast by cast.
 */
export function announcementProblem(pool: MagicPool, casts: readonly AnnouncedSpell[]): string | null {
  // "A unit may not be targeted by more than one Lightning Strike per magic action."
  const struck = new Set<string>()
  for (const cast of casts) {
    if (cast.spell !== 'lightning_strike' || cast.target.kind !== 'units') continue
    for (const id of cast.target.unitIds) {
      if (struck.has(id)) return 'a unit may not be targeted by more than one Lightning Strike'
      struck.add(id)
    }
  }

  // "Combined castings are one spell with a bigger number" -- so one spell at one
  // target is one entry with a count. Two entries resolved twice: two Hailstorms made
  // two save rolls, and two Flash Floods set two bars of six rather than one of twelve.
  // Both clients merge a repeat through `stageCast`, so only a hand-built action ever
  // reached this; it is refused rather than quietly resolved the wrong way. After the
  // Lightning Strike rule, which says the same thing about one spell more precisely.
  for (const [i, cast] of casts.entries()) {
    if (casts.slice(0, i).some((c) => c.spell === cast.spell && sameSpellTarget(c.target, cast.target))) {
      return `${spell(cast.spell).name} is announced twice at one target; combine the castings instead`
    }
  }

  // Paying for it: the whole spend within the roll, and then a split of the pool that
  // pays each spell in its element and, for a species spell, its species (v2 Phase 1).
  // For a single-species pool the second is the first -- one supplier holds it all.
  const spent = casts.reduce((sum, cast) => sum + spell(cast.spell).cost * cast.count, 0)
  if (spent > pool.points) {
    return `announced ${spent} magic worth of spells with only ${pool.points} rolled`
  }
  return allocationProblem(pool, casts.map(demandOf))
}

/**
 * Why this announced cast is illegal, or null.
 *
 * The per-spell rules that a list of targets cannot express, because they depend on
 * the number of castings or on the rest of the announcement. Separate from
 * `spellTargets` for that reason: one answers "what may I aim at", this answers "may I
 * aim *this* at it, for *this* much".
 */
export function spellTargetProblem(state: GameState, cast: AnnouncedSpell): string | null {
  const s = spell(cast.spell)

  if (s.id === 'resurrect_dead' && cast.target.kind === 'units') {
    // "...units in your DUA that contains the element of magic used to cast this
    // spell." The health budget is on the offer as `minCount`; this is the half that
    // depends on which element paid, and it bites only when a Standing Stones has lent
    // the pool an element the caster's species does not carry.
    for (const id of cast.target.unitIds) {
      const unit = state.units[id]
      if (unit === undefined) continue
      const elements = speciesElements(unitType(unit.typeId).species)
      if (!elements.includes(cast.element)) {
        return `${unitType(unit.typeId).name} does not contain ${cast.element}`
      }
    }
  }

  return null
}

/**
 * Every spell this pool could cast, for the announcement prompt.
 *
 * Pure -- no `GameState` -- so it is testable from a pool literal the way
 * `saiEffects` is testable from a face literal. The board question (which elements,
 * how many points) is answered by `magicPool` before this is called.
 *
 * It filters on `resolvesSpell`, which is what makes a half-built rung *playable*: a
 * spell the rules being played cannot resolve is never offered, so the throw behind
 * it guards only against a spell added to `data/` with no code behind it.
 */
export function castableSpells(
  state: GameState,
  caster: PlayerId,
  pool: MagicPool,
  ruleSet: RuleSet,
): readonly Castable[] {
  const force = forceSpecies(state, caster)
  const out: Castable[] = []

  for (const s of SPELLS) {
    if (!resolvesSpell(s.id, ruleSet)) continue
    // A single-species pool is checked against the force's species here; a mixed one
    // is checked per supplier just below, which is the same question asked per die.
    if (
      pool.suppliers === undefined &&
      s.species !== 'any' &&
      !force.some((species) => spellAllowsSpecies(s, species))
    ) {
      continue
    }
    if (pool.cantripOnly === true && !s.cantrip) continue
    if (pool.fromReserves === true && !s.reserves) continue

    // What could pay for this spell at all: the suppliers of its species, capped by
    // the roll. For a single-species pool that is the pool.
    const paying = payers(pool).filter((p) => p.pays(s.species))
    const reach = Math.min(pool.points, paying.reduce((sum, p) => sum + p.points, 0))
    if (s.cost > reach) continue

    let elements = pool.elements.filter(
      (e) => spellAcceptsElement(s, e) && paying.some((p) => p.elements.includes(e)),
    )
    // "...units in your DUA that contains the element of magic used to cast this
    // spell." Filtered to the elements your species carry, so it bites only when a
    // Standing Stones has lent the pool an element none of them does; which target
    // takes which element is `spellTargetProblem`'s, per unit.
    if (s.id === 'resurrect_dead') {
      const own = force.flatMap((species) => speciesElements(species))
      elements = elements.filter((e) => own.includes(e))
    }
    if (elements.length === 0) continue

    // A spell with nowhere to land is dropped rather than offered -- the same rule
    // that drops a targeting SAI whose army holds nothing small enough to take.
    // "The target of a spell, **or the conditions for a spell's effect to occur**, must
    // exist at the time the target is selected" (p. 13). Summon Dragon is the first
    // spell with a condition beyond its target: a terrain is only a target if some
    // dragon of a colour this pool can pay for could actually be summoned to it.
    if (s.id === 'summon_dragon') {
      elements = elements.filter((e) =>
        TERRAIN_SLOTS.some((slot) => summonable(state, e, slot).length > 0),
      )
      if (elements.length === 0) continue
    }

    let targets = spellTargets(state, caster, s).filter((t) => t.minCount * s.cost <= reach)
    // A mixed force's dead are of more than one species: a unit whose species carries
    // none of these elements could never be raised by this casting, so it is not offered,
    // and one carrying only some of them says which (`SpellTargetOffer.elements`).
    if (s.id === 'resurrect_dead') {
      const offered = elements
      targets = targets.flatMap((t): SpellTargetOffer[] => {
        if (t.target.kind !== 'units') return [t]
        let raising: readonly Element[] = offered
        for (const id of t.target.unitIds) {
          const unit = state.units[id]
          if (unit === undefined) return []
          const carries = speciesElements(unitType(unit.typeId).species)
          raising = raising.filter((e) => carries.includes(e))
        }
        if (raising.length === 0) return []
        return raising.length < offered.length ? [{ ...t, elements: raising }] : [t]
      })
    }
    if (s.id === 'summon_dragon') {
      targets = targets.filter(
        (t) =>
          t.target.kind === 'terrain' &&
          elements.some((e) => summonable(state, e, t.target.kind === 'terrain' ? t.target.slot : 'frontier').length > 0),
      )
    }
    if (targets.length === 0) continue

    out.push({
      spell: s,
      elements,
      maxCount: s.cumulative ? Math.floor(reach / s.cost) : 1,
      // A target needing more castings than the pool can buy is not a target.
      targets: targets.filter((t) => t.minCount * s.cost <= reach),
    })
  }

  return out
}

/**
 * "7 magic (water or earth)" -- the sentence every magic prompt and every magic log
 * line opens with.
 *
 * Here rather than in either client, for `saiPhrase`'s reason: the first draft of a
 * shared sentence gets written twice, and that is how the browser and the terminal
 * start describing one roll differently. Element names are the element ids -- there
 * is no display table to consult, and `ELEMENT_NAME` in `Elements.tsx` is an identity
 * map that exists as a place to hang one later.
 */
export function magicRolled(pool: MagicPool): string {
  const which = poolSplit(pool.suppliers) ?? elementList(pool.elements)

  const limit =
    pool.cantripOnly === true
      ? ', cantrip spells only'
      : pool.fromReserves === true
        ? ', reserve spells only'
        : ''

  return `${pool.points} magic (${which}${limit})`
}

/** "water or earth", or "no element". */
function elementList(elements: readonly Element[]): string {
  const [last, ...front] = [...elements].reverse()
  return last === undefined
    ? 'no element'
    : front.length === 0
      ? last
      : `${front.reverse().join(', ')} or ${last}`
}

/**
 * "5 Treefolk: water or earth; 3 Firewalkers: fire or air" -- a mixed pool's split, or
 * null for a single-species one. The answer to "why can't I cast this?" that one number
 * could not give (v2 Phase 1). Both clients print it for a `magic_rolled` entry that
 * carries suppliers, and `magicRolled` opens every mixed magic prompt with it.
 */
export function poolSplit(suppliers: readonly MagicSupplier[] | undefined): string | null {
  if (suppliers === undefined) return null
  return suppliers
    .map(
      (s) =>
        `${s.points} ${s.species === null ? 'from no die' : speciesName(s.species)}: ${elementList(s.elements)}`,
    )
    .join('; ')
}

/**
 * What both clients print under a spell whose rulebook text says "target any army" and
 * whose data says `own_army` -- the house rule (Phase 9a). One sentence, here, so the
 * browser and the terminal cannot explain it two ways.
 */
export const OWN_ARMY_NOTE = 'House rule: a helpful spell targets only your own armies.'

/**
 * Two announced targets naming the same thing.
 *
 * One copy, in the engine, because three things ask it: the applier validating an
 * announcement, and both clients' drafts merging a repeat casting into a combined
 * one. Three copies of "are these the same army" is how two of them end up
 * disagreeing about a Reserve Army.
 */
export function sameSpellTarget(a: SpellTarget, b: SpellTarget): boolean {
  if (a.kind !== b.kind) return false
  switch (a.kind) {
    case 'none':
      return true
    case 'army':
      return b.kind === 'army' && a.player === b.player && a.army === b.army
    case 'terrain':
      return b.kind === 'terrain' && a.slot === b.slot
    case 'dua':
      return b.kind === 'dua' && a.player === b.player
    case 'units':
      return (
        b.kind === 'units' &&
        a.unitIds.length === b.unitIds.length &&
        a.unitIds.every((id) => b.unitIds.includes(id))
      )
  }
}

/**
 * What a client is part-way through announcing: a spell, and the element paying for it
 * once that is settled.
 *
 * Both clients hold one of these between taps. It is here rather than in either of
 * them for `spellPlan`'s reason -- the terminal and the browser ask the same three
 * questions in the same order, and two copies of "which half of the answer do I have"
 * is how they stop agreeing.
 */
export interface SpellAim {
  readonly spell: string
  readonly element?: Element
  /**
   * How many castings the next target takes (Phase 9f), set by the picker's stepper
   * before the target is tapped -- so three Stone Skins on one army is one tap, not three
   * trips through spell and target. Absent means one. Ignored where the count buys
   * nothing (`Spell.countScales`) or where the target sets it (`minCount`).
   */
  readonly count?: number
}

/** The castings one staged target takes: the stepper's number where it scales the
 *  spell, never less than the target's own price, and one for everything else. */
export function castingsFor(aim: SpellAim, s: Spell, minCount: number): number {
  const asked = s.cumulative && s.countScales ? (aim.count ?? 1) : 1
  return Math.max(asked, minCount)
}

/** One staged cast in a client's announcement draft. */
export interface SpellDraftCast {
  readonly spell: string
  readonly element: Element
  readonly count: number
  readonly target: SpellTarget
}

/** A spell the picker can offer, with its price against what is left unspent. */
export interface SpellOffer {
  readonly castable: Castable
  /** How many more castings the remaining budget could buy. 0 means "greyed out". */
  readonly affordable: number
}

export interface SpellPlan {
  readonly spent: number
  readonly remaining: number
  /**
   * Why the staged casts cannot all be paid for, or null -- `announcementProblem` on the
   * draft, so a client can say why Confirm is off rather than only that it is. Null for
   * every draft a client builds from `affordable`, and for any single-species draft
   * within `remaining`; a mixed pool is where a choice of element can strand a spell.
   */
  readonly problem: string | null
  /** Every castable spell, affordable or not -- a picker that hides what you cannot
   *  afford cannot tell you what you were short of. */
  readonly offers: readonly SpellOffer[]
  /** The answer, once the player is done. */
  readonly casts: readonly SpellDraftCast[]
}

/**
 * The spell picker, as a pure function over a staged draft.
 *
 * The Reinforce Step's pattern (`reinforcePlan`): the sheet stages casts and **one**
 * action reaches the engine, rather than a component holding wizard state or
 * dispatching per spell. The rules announce every spell at once and choose the
 * resolution order afterwards, so a per-spell dispatch would answer a question nobody
 * asked.
 *
 * In the engine rather than in `prompts.ts` because the terminal needs it too, and
 * `src/cli` has never depended on `src/ui`. Same reason `saiPhrase` sits in `roll.ts`.
 *
 * Staged casts are filtered against the live offer rather than trusted: a draft
 * outlives nothing, and it costs one line to make that true instead of assumed.
 */
export function spellPlan(
  castable: readonly Castable[],
  pool: MagicPool,
  staged: readonly SpellDraftCast[],
): SpellPlan {
  const offered = new Map(castable.map((c) => [c.spell.id, c]))

  const casts = staged.filter((cast) => {
    const offer = offered.get(cast.spell)
    return (
      offer !== undefined &&
      cast.count >= 1 &&
      (offer.spell.cumulative || cast.count === 1) &&
      elementsFor(offer, cast.target).includes(cast.element) &&
      offer.targets.some((t) => sameSpellTarget(t.target, cast.target) && cast.count >= t.minCount)
    )
  })

  const spent = casts.reduce(
    (sum, cast) => sum + (offered.get(cast.spell)?.spell.cost ?? 0) * cast.count,
    0,
  )
  const remaining = pool.points - spent

  return {
    spent,
    remaining,
    problem: announcementProblem(pool, casts),
    offers: castable.map((c) => ({ castable: c, affordable: affordableMore(pool, casts, c, remaining) })),
    casts,
  }
}

/**
 * How many more castings of an offer the pool could pay for on top of a draft.
 *
 * The remaining budget bounds it, and for a single-species pool that is the answer --
 * v1's arithmetic exactly. A mixed pool asks the allocation too, trying each element
 * the offer accepts, because what is left may be the wrong species' or the wrong
 * colour: three Treefolk points left over do not buy a Firewalker spell.
 */
function affordableMore(
  pool: MagicPool,
  staged: readonly SpellDraftCast[],
  offer: Castable,
  remaining: number,
): number {
  const cost = offer.spell.cost
  const bound = offer.spell.cumulative
    ? Math.floor(remaining / cost)
    : Math.min(1, Math.floor(remaining / cost))
  if (pool.suppliers === undefined) return bound

  const demands = staged.map(demandOf)
  for (let k = bound; k > 0; k--) {
    const fits = offer.elements.some(
      (element) =>
        allocationProblem(pool, [...demands, { species: offer.spell.species, element, points: cost * k }]) ===
        null,
    )
    if (fits) return k
  }
  return 0
}

/**
 * Stage one more casting into a draft: a repeat of a spell at a target it is already
 * aimed at *merges* into that entry's count, because combined castings are one spell
 * with a bigger number rather than two spells.
 *
 * A second casting of a **non-cumulative** spell at the same target buys nothing, so
 * the draft comes back unchanged. Until Phase 9a both clients merged blindly -- and a
 * second tap on the same Lightning Strike target staged `count: 2`, which `reduce`
 * refuses with a throw the browser does not catch. One copy, here, for the reason
 * `sameSpellTarget` has one.
 */
export function stageCast(
  castable: readonly Castable[],
  staged: readonly SpellDraftCast[],
  cast: SpellDraftCast,
): readonly SpellDraftCast[] {
  const at = staged.findIndex((c) => c.spell === cast.spell && sameSpellTarget(c.target, cast.target))
  if (at === -1) return [...staged, cast]

  const offer = castable.find((c) => c.spell.id === cast.spell)
  if (offer === undefined || !offer.spell.cumulative) return staged

  const merged = [...staged]
  merged[at] = { ...cast, count: (staged[at]?.count ?? 0) + cast.count }
  return merged
}

/** Whether a non-cumulative spell is already staged at this target, so that a second
 *  casting would buy nothing -- what a client greys out rather than offers. */
export function repeatBuysNothing(
  staged: readonly SpellDraftCast[],
  spellId: string,
  target: SpellTarget,
): boolean {
  return (
    !spell(spellId).cumulative &&
    staged.some((c) => c.spell === spellId && sameSpellTarget(c.target, target))
  )
}

/**
 * "your army at the Frontier" -- what a target reads as on a button.
 *
 * `name` is passed in because the two clients name a terrain differently: the browser
 * says "Your home" from the human's point of view, the terminal has its own table.
 * The *join* is here, so they cannot drift into describing one target two ways.
 */
export function spellTargetLabel(
  target: SpellTarget,
  human: PlayerId,
  name: (ref: ArmyRef) => string,
  unitName: (id: string) => string,
  /**
   * Where a named unit is standing, or null for one in the DUA.
   *
   * **A unit target is not identified by its name**, which is the bug this closes:
   * Lightning Strike, Mirage and Path each offer one button per unit, and a force
   * fields several dice of one type across three armies -- so the list read
   * "Pine, Pine, Pine, Pine" and picking the right one was guesswork. The name plus
   * the place is what a player actually sees on the board.
   *
   * Resurrect Dead's targets are in the DUA, which is not a place you could confuse
   * with another, so a null reads as the bare name.
   */
  where: (id: string) => ArmyRef | null = () => null,
): string {
  switch (target.kind) {
    case 'none':
      return 'no target'
    case 'dua':
      return `${target.player === human ? 'your' : "the enemy's"} DUA`
    case 'terrain':
      return name(target.slot)
    case 'army':
      return `${target.player === human ? 'your' : "the enemy's"} army at ${name(target.army)}`
    case 'units': {
      const named = target.unitIds.map(unitName).join(', ')
      // One place or none: every spell in scope targets units in a single army, so
      // a second terrain here would mean a rule changed rather than a label.
      const ref = target.unitIds.map(where).find((r) => r !== null) ?? null
      return ref === null ? named : `${named} at ${name(ref)}`
    }
  }
}
