/**
 * Die Roll Resolution, steps 5 to 10 (full rules p. 27).
 *
 * v0 computed a roll as a sum. The rules compute it as an ordered pipeline, and the
 * order is the whole point -- subtract before divide gives a different answer than
 * divide before subtract -- and every v1 feature attaches to a numbered step of it:
 *
 *   5  subtotal all non-SAI results
 *   6  subtract        (never below 0; ID results are removed last)
 *   7  divide          (round down; at most one divider per result type)
 *   8  add SAI results (they are never divided)
 *   9  multiply        (at most one multiplier per result type)
 *   10 add             (including every "counts as" conversion -- see `counts_as`,
 *                       which `resolveFaces` turns into an `add` once the dice land)
 *
 * **The running value is a triple per result type, not a number**, and that is
 * forced by two lines of the rules rather than chosen: "ID results are the last
 * results to be removed" by steps 6 and 7, and SAI results join only at step 8,
 * after the divide. Collapse the triple into a subtotal and neither can be
 * expressed. It collapses at step 10 and not before.
 *
 * Steps 1, 3 and 4 -- rolling, rerolls and applying SAIs -- live in `roll.ts` and
 * `sai.ts`; step 2's delayed effects are Phase 4. Nothing produces a `Modifier` yet
 * except the eighth face; the steps still run, and the tests drive them with
 * hand-built lists, so the ordering is settled before anything depends on it.
 */
import type { ResultType } from '../data/types'

/**
 * What a multiplier at step 9 applies to.
 *
 * `all` is the ordinary case. `id` is the eighth face -- "when rolling the army,
 * all ID results are doubled, for any roll" -- which multiplies the ID share alone,
 * so it needs the split the pipeline is already keeping for step 6.
 */
export type ModifierShare = 'all' | 'id'

/**
 * A roll modifier, named by the step that applies it.
 *
 * `source` is **display only** (v1 Phase 9c): the spell, SAI, breath or rule that put it
 * there, stamped by `armyRoll` from `Effect.source`. Nothing in the arithmetic reads it.
 * It exists so a roll can say "− 4 Galeforce" instead of an unexplained `12 → 8`.
 *
 * `fromSpell` says the modifier came from a spell (v2 Phase 6b), which a rule reads:
 * Counter's riposte and Charge's melee "may only be reduced by save results generated
 * by spells". Stamped when the modifier is gathered, never stored on the `Effect` --
 * `state.effects` is in the golden digest and a modifier never reaches `GameState`, so
 * the mark moves no recorded game.
 */
export type Modifier = ModifierBody & { readonly source?: string; readonly fromSpell?: true }

type ModifierBody =
  | { readonly kind: 'subtract'; readonly resultType: ResultType; readonly amount: number }
  | { readonly kind: 'divide'; readonly resultType: ResultType; readonly by: number }
  | {
      readonly kind: 'multiply'
      readonly resultType: ResultType
      readonly by: number
      readonly share: ModifierShare
    }
  | { readonly kind: 'add'; readonly resultType: ResultType; readonly amount: number }
  /**
   * The Death dragon's breath: "the army ignores all of its ID results until the
   * beginning of its next turn" (full rules p. 20).
   *
   * A modifier of its own rather than a `multiply` by zero, for two reasons. It is
   * not a step-9 multiplier, so it must not eat that type's one-multiplier budget --
   * an army holding an eighth face would otherwise throw rather than roll. And it
   * happens before step 6's subtract, because an ID result the army is ignoring was
   * never there to be subtracted from.
   */
  | { readonly kind: 'ignore_ids'; readonly resultType: ResultType }
  /**
   * Flaming Shields (v1 Phase 8): "Firewalkers may count save results as if they were
   * melee results" -- a **"counts as"**, which p. 28 makes "a modifier that adds",
   * applied at step 10.
   *
   * A *permission*, not an amount, and that is why it is not simply an `add`: how many
   * save results the dice rolled is not known until they land, and in a combination
   * roll that also counts saves the owner chooses how many to move. So `armyRoll`
   * gathers this onto the melee type and `resolveFaces`, which can read the dice,
   * turns it into the `add` it becomes. `applyModifiers` ignores it.
   *
   * "Only rolled results may be counted in this way. Results generated by spells may
   * never be counted as another type" -- so what converts is the save results on the
   * dice, and never a Stone Skin's.
   *
   * **`species` says whose dice** (v2 Phase 1): "*Firewalkers* may count save results",
   * so in a mixed army only the Firewalker dice convert and a Treefolk save beside them
   * stays a save. The modifier is gathered per army and applied per die, which is why
   * it names the species rather than being present or absent. Modifiers never reach
   * `GameState`, so the field moves no golden.
   */
  | {
      readonly kind: 'counts_as'
      /**
       * A "counts as" is a pair of result types and a rule about when it applies
       * (v2 Phase 6b): Flaming Shields' saves as melee, not on a counter-attack; Coastal
       * Dodge's maneuver as saves, on any roll. `conversionsIn` in `roll.ts` is the one
       * resolver, so a new ability is a new row -- a factory below -- and no new
       * function beside `convertsSaves` and `dodgesManeuver`, which it replaced.
       */
      readonly from: ConvertibleType
      readonly resultType: ConvertibleType
      /** Which rolls it applies to, by whether the roll is a counter-attack. */
      readonly counter: 'never' | 'only' | 'either'
      readonly species: readonly string[]
    }

/** The result types a "counts as" in scope moves between. */
export type ConvertibleType = 'melee' | 'save' | 'maneuver'

/** Flaming Shields' permission, as `armyRoll` gathers it: the dice of these species
 *  may count their rolled saves as melee, except when making a counter-attack. */
export function savesAsMelee(species: readonly string[]): Modifier {
  return {
    kind: 'counts_as',
    from: 'save',
    resultType: 'melee',
    counter: 'never',
    species,
    source: 'Flaming Shields',
  }
}

/**
 * Coastal Dodge's permission (v2 Phase 5d): "When at a terrain that contains water, Coral
 * Elves may count maneuver results as if they were save results." Gathered at every
 * water terrain whatever the roll, and applied only by a roll that counts saves and not
 * maneuver -- where converting can only help, so it is automatic.
 */
export function maneuverAsSaves(species: readonly string[]): Modifier {
  return {
    kind: 'counts_as',
    from: 'maneuver',
    resultType: 'save',
    counter: 'either',
    species,
    source: 'Coastal Dodge',
  }
}

/**
 * Mountain Mastery's permission (v2 Phase 6f): "When at a terrain that contains earth,
 * Dwarves may count melee results as if they were maneuver results." Gathered at every
 * earth terrain, and applied by a roll that counts maneuver and not melee -- every
 * maneuver roll there is, and a Dwarf's own maneuver sub-roll -- where it only adds.
 */
export function meleeAsManeuver(species: readonly string[]): Modifier {
  return {
    kind: 'counts_as',
    from: 'melee',
    resultType: 'maneuver',
    counter: 'either',
    species,
    source: 'Mountain Mastery',
  }
}

/**
 * Dwarven Might's permission (v2 Phase 6f): "When at a terrain that contains fire, Dwarves
 * may count save results as if they were melee results when rolling for a
 * counter-attack." Flaming Shields' pair with the opposite clause: only on a
 * counter-attack, which counts melee and not saves, so it only adds.
 */
export function savesAsMeleeOnCounter(species: readonly string[]): Modifier {
  return {
    kind: 'counts_as',
    from: 'save',
    resultType: 'melee',
    counter: 'only',
    species,
    source: 'Dwarven Might',
  }
}

/** The eighth-face holder's doubled ID results, as the step-9 modifier it is. */
export function doubleIdsModifier(resultType: ResultType): Modifier {
  return { kind: 'multiply', resultType, by: 2, share: 'id', source: 'Eighth face' }
}

/** Every result type, for an effect that speaks about a roll rather than a type. */
export const ALL_RESULT_TYPES: readonly ResultType[] = [
  'melee',
  'missile',
  'magic',
  'save',
  'maneuver',
]

/** Death breath, as one modifier per result type -- it applies to every roll. */
export function ignoreIdsModifiers(): readonly Modifier[] {
  return ALL_RESULT_TYPES.map((resultType) => ({ kind: 'ignore_ids', resultType }) as const)
}

/**
 * Everything a roll produces that is not a number -- damage owed in the other
 * direction, damage no save can stop, a counter-attack refused. Phase 4 adds
 * targeting and free moves.
 *
 * Rerolls are deliberately *not* here. They happen at step 3, inside the roll, and
 * an effect handed back to the caller could not be applied before the totals the
 * caller is being given were computed. `SaiOutcome.reroll` carries them instead.
 */
export type RollEffectBody =
  /** Counter and Volley: damage straight back at the attacking army, which gets no
   *  save roll of its own. */
  | { readonly kind: 'riposte'; readonly damage: number }
  /** Smite: damage the defender's save total does not reduce. */
  | { readonly kind: 'unsavable'; readonly damage: number }
  /** Surprise: the defending army may not counter-attack. */
  | { readonly kind: 'suppress_counter' }
  /**
   * Cantrip's second sentence (Phase 7f): magic results from a roll that is not a
   * magic action, and which buy only spells marked `C`.
   *
   * Not `results`, because these are not the roll's own currency -- a melee roll does
   * not count magic, and the pool they make is spent on spells rather than added to
   * anything. So they leave the roll as an effect and the march step opens a small
   * casting window for them.
   */
  | { readonly kind: 'cantrip'; readonly points: number }
  /**
   * Bullseye, Double Strike, Smother, Firecloud, Seize, Flame: pick health-worth of
   * units out of the army this roll is aimed at, and do something to them.
   *
   * One member for six SAIs, because what separates them is three orthogonal axes and
   * not a name. The name rides on `RollEffect.sai` for the log; nothing in the engine
   * branches on it, which is what stops this becoming a second dispatch table beside
   * `sai.ts`'s.
   */
  | {
      readonly kind: 'target_enemy'
      /**
       * Health-worth to pick. A *budget*, not a result count -- `2 SAI:Flame` targets
       * two health-worth -- which is the same rule as everywhere else in `sai.ts`:
       * the number printed on the face is the answer, and each SAI says what its own
       * number means.
       */
      readonly health: number
      /**
       * How a target gets out of it: by its own roll, or not at all.
       *
       * `'save'` and `'maneuver'` are questions about a *total* -- "those that do not
       * generate a save result are killed" -- and `'id'` is a question about a face,
       * which is why Seize rolls its targets without resolving them.
       */
      readonly escape: 'none' | 'save' | 'maneuver' | 'id'
      /**
       * What happens to a target that did not escape.
       *
       * `'reserve'` is Roar (v2 Phase 6d): moved to the Reserve Area, and not killed --
       * no death trigger. `'save_or_bury'` is Stomp's: killed, and then the dead roll
       * saves, and those that generate none are buried -- Fire breath's check, rolled a
       * machine step later so an Accelerated Growth exchange is settled first.
       */
      readonly fate: 'kill' | 'bury' | 'reserve' | 'save_or_bury'
      /**
       * Where a target that escaped ends up. Omitted means "where it was standing",
       * which is every escape but Seize's.
       *
       * Stated rather than inferred from `escape: 'id'`. That inference is true of the
       * one ID-escape SAI in this box and false of Swallow, which kills and buries on
       * the same test -- the Genie's-4 mistake again. Optional-and-omitted because a
       * `TargetTask` built from this lands in `combat.attack`, and so in the golden
       * digest.
       */
      readonly escapeTo?: 'reserve'
      /**
       * Swallow (v2 Phase 5c): "target **one unit**" -- one die whatever its health, so
       * `health` is not read and the task is never combined (p. 32: SAIs that target an
       * individual unit "are always resolved one by one"). Sleep's rule, on a task that
       * otherwise rolls and buries exactly like Seize and Flame. Omitted everywhere else.
       */
      readonly one?: true
    }
  /**
   * Sleep: one *unit* in an opposing army at this terrain, asleep until the roller's
   * next turn.
   *
   * No parameters at all -- not even a count. "Target one unit" means one die whatever
   * its health, which is why it cannot ride on `target_enemy`'s health budget, and p.
   * 32 names individual-unit SAIs among the ones that are never combined.
   */
  | { readonly kind: 'sleep' }
  /**
   * Galeforce: one opposing *army*, at any terrain, minus four save and four maneuver
   * until the roller's next turn.
   *
   * Also parameterless: the reference says four, flatly, and not X. The `4` on the
   * Genie's face is a coincidence of it being a monster face, which is exactly why
   * reading it would be wrong.
   */
  | { readonly kind: 'galeforce' }
  /**
   * Choke: kill up to X health-worth of the defenders **that rolled an ID icon**, and
   * do not count their results.
   *
   * A *delayed* effect -- "this effect is applied when resolving Delayed Effects",
   * which is step 2 of the pipeline, when the defender's save dice have landed and
   * before anything has been counted. It cannot ride on `target_enemy`, which is
   * chosen before the save roll exists: the whole question is which dice came up ID.
   */
  | { readonly kind: 'choke'; readonly health: number }
  /**
   * Confuse: reroll up to X health-worth of the defenders, "ignoring all previous
   * results".
   *
   * Also step 2, and note what makes it different from every other reroll in the game:
   * step 3's rerolls *add* a die to the roll and both faces count, while this one
   * **replaces** the face. A die that is confused was never rolled, as far as the
   * total is concerned.
   */
  | { readonly kind: 'confuse'; readonly health: number }
  /**
   * Wild Growth: X split between save results and promotions, however the roller
   * likes.
   *
   * The first effect that is *friendly* -- it reaches into the roller's own army --
   * and the first whose answer is a number the roll then has to use, which is what
   * `RollSpec.saiResults` has been waiting for since Phase 4a.
   */
  | { readonly kind: 'wild_growth'; readonly budget: number }
  /**
   * Firewalking and Teleport: "this unit may move itself and up to three health-worth
   * of units in its army to any terrain."
   *
   * `unitId` is not on the body -- `resolveRoll` stamps it, and it matters here rather
   * than only for the log, because *this unit* is the one that has to move. `health`
   * is the three the reference states, and unlike Flame's "two" it does **not** agree
   * with the count on any of the three faces that carry these (all of them are 4). So
   * it is a constant, for Galeforce's reason: the number on a monster face is a fact
   * about monster faces.
   */
  | { readonly kind: 'free_move'; readonly health: number }
  /**
   * Wave (v2 Phase 5c): X off the *other* army's roll in the same exchange. "During a
   * melee attack, the defending army subtracts X save results. During a maneuver roll
   * while marching, subtract X from each counter-maneuvering army's maneuver results."
   *
   * The first SAI that modifies a roll it is not part of, with no duration: Galeforce
   * reaches the other army too, but through `state.effects` and until a turn ends. This
   * lives only as long as the exchange or the contest, so it rides the parked roll
   * (`PendingSaves.wave`) or is read straight off the marcher's dice.
   */
  | { readonly kind: 'wave'; readonly amount: number }
  /**
   * Hypnotic Glare (v2 Phase 5c): every defender whose save die came up an ID is
   * hypnotized, and none of their results count. Delayed, like Choke -- the question is
   * which dice came up ID -- but it picks nobody: "all units that roll an ID icon". So
   * it owes no decision, and the delayed pause applies it on its own.
   */
  | { readonly kind: 'glare' }
  /**
   * Bash (v2 Phase 6d), in a save roll against a melee attack: "target one unit from the
   * attacking army. The targeted unit takes damage equal to the melee results it
   * generated. The targeted unit must make a save roll against this damage. Bash also
   * generates save results equal to the targeted unit's melee results."
   *
   * The first decision the *defender* owes about the *attacker's* dice, and the first
   * whose number is not on its own face: X is read only "during other save rolls".
   * Chosen at the delayed pause, where the save dice are down and the attack's are still
   * parked beside them.
   */
  | { readonly kind: 'bash' }
  /**
   * Bash in the dragon combination roll: "choose an attacking dragon that has inflicted
   * damage. That dragon takes damage equal to the amount of damage it inflicted. Bash
   * also generates save results equal to the damage the chosen dragon did."
   *
   * The dragon roll has no queue to ask on (`noSideDecision`), so the choice is a house
   * rule: the dragon that did the most, which maximises both halves (`RULES-V0.md`
   * section 18). Resolved by `finishDragonDamage`, which is where the damage is known.
   */
  | { readonly kind: 'bash_dragon' }
  /**
   * Charge (v2 Phase 6e): this melee attack is a charge. No number -- several are one --
   * and nothing to decide; `attackFacts` reads it, and `resolveFaces` has already turned
   * the attacking army's maneuver into melee by the time it does.
   */
  | { readonly kind: 'charge' }

/** A `RollEffectBody` once `resolveRoll` has stamped it with the die that made it,
 *  so the log can say *which* Fireshadow smote you. */
export type RollEffect = RollEffectBody & {
  /** A plain `string` rather than `UnitId`: this file stays clear of `GameState`. */
  readonly unitId: string
  readonly sai: string
}

/** How many ID results each result type receives. See `allocateIds`. */
export type IdAllocation = Readonly<Partial<Record<ResultType, number>>>

/**
 * One result type mid-pipeline.
 *
 * `sai` is separate from `normal` rather than merged into it because step 8 adds it
 * after step 7 has divided. Once step 8 has run the two are the same thing, and it
 * is folded in.
 */
export interface Share {
  readonly id: number
  readonly normal: number
  readonly sai: number
}

const totalOf = (share: Share): number => share.id + share.normal + share.sai

/**
 * Step 6. Results can never go below 0, and ID results are the last to be removed,
 * so the subtraction eats the normal share first.
 */
function subtract(share: Share, amount: number): Share {
  const fromNormal = Math.min(share.normal, amount)
  return {
    id: Math.max(0, share.id - (amount - fromNormal)),
    normal: share.normal - fromNormal,
    sai: share.sai,
  }
}

/**
 * Step 7. Round down, and again remove the normal share first -- what survives a
 * halving is as much ID as possible, which matters when step 9 then doubles the ID
 * share alone.
 */
function divide(share: Share, by: number): Share {
  if (by <= 0) throw new Error(`a divide modifier needs a positive divisor, got ${by}`)
  const before = share.id + share.normal
  const after = Math.floor(before / by)
  const normal = Math.max(0, share.normal - (before - after))
  return { id: after - normal, normal, sai: share.sai }
}

function atMostOne(modifiers: readonly Modifier[], what: string): void {
  if (modifiers.length > 1) {
    const first = modifiers[0]
    throw new Error(
      `${modifiers.length} ${what} modifiers on ${first?.resultType ?? '?'} results; ` +
        `the rules allow at most one per result type`,
    )
  }
}

/**
 * Steps 6 to 10 for one result type, in that order.
 *
 * Takes the whole modifier list and picks out its own type rather than trusting the
 * caller to have filtered: the one-per-type rules below are only meaningful if this
 * function is the thing deciding what "per type" means.
 *
 * Exported because the order is the thing worth testing, and testing it through a
 * roll would mean testing it through the dice.
 */
export function applyModifiers(
  share: Share,
  resultType: ResultType,
  all: readonly Modifier[],
): number {
  const modifiers = all.filter((m) => m.resultType === resultType)
  let value = share

  // Before step 6: an ID result the army is ignoring is not there to be subtracted
  // from, halved, or doubled by an eighth face later on.
  if (modifiers.some((m) => m.kind === 'ignore_ids')) value = { ...value, id: 0 }

  for (const modifier of modifiers) {
    if (modifier.kind === 'subtract') value = subtract(value, modifier.amount)
  }

  const dividers = modifiers.filter((m) => m.kind === 'divide')
  atMostOne(dividers, 'divide')
  for (const modifier of dividers) value = divide(value, modifier.by)

  // Step 8: SAI results join here, undivided, and are ordinary non-ID results from
  // now on.
  value = { id: value.id, normal: value.normal + value.sai, sai: 0 }

  // "There may never be more than one modifier that multiplies applied to each type
  // of result" (p. 28), counted per type and not per share: the eighth face's ID
  // doubling *is* that type's one multiplier. Nothing in v1 can produce a second
  // one until spells arrive in Phase 7, so the strict reading costs nothing now and
  // refuses to invent arithmetic the rulebook does not describe.
  const multipliers = modifiers.filter((m) => m.kind === 'multiply')
  atMostOne(multipliers, 'multiply')
  for (const modifier of multipliers) {
    value =
      modifier.share === 'id'
        ? { ...value, id: value.id * modifier.by }
        : { id: value.id * modifier.by, normal: value.normal * modifier.by, sai: 0 }
  }

  for (const modifier of modifiers) {
    if (modifier.kind === 'add') value = { ...value, normal: value.normal + modifier.amount }
  }

  return Math.max(0, totalOf(value))
}

/**
 * Step 5's other half: which type each ID result counts as.
 *
 * With one kind there is nothing to decide. With several -- a dragon's combination
 * roll -- the owner chooses, and the pool has to be spent exactly, or an ID is
 * either counted twice or dropped.
 */
export function allocateIds(
  pool: number,
  kinds: readonly ResultType[],
  allocation: IdAllocation | undefined,
): ReadonlyMap<ResultType, number> {
  const primary = kinds[0]
  if (primary === undefined) throw new Error('a roll needs at least one result type')

  if (kinds.length === 1) {
    if (allocation !== undefined) {
      throw new Error('a single-type roll has no ID allocation to make')
    }
    return new Map([[primary, pool]])
  }

  if (allocation === undefined) {
    throw new Error(
      `a combination roll (${kinds.join('+')}) needs an ID allocation: ` +
        `the owner chooses what each ID counts as`,
    )
  }

  for (const kind of Object.keys(allocation)) {
    if (!kinds.includes(kind as ResultType)) {
      throw new Error(`the ID allocation names ${kind}, which this roll does not count`)
    }
  }

  const spent = new Map<ResultType, number>()
  let total = 0
  for (const kind of kinds) {
    const share = allocation[kind] ?? 0
    if (!Number.isInteger(share) || share < 0) {
      throw new Error(`the ID allocation gives ${kind} ${share}, which is not a count of results`)
    }
    spent.set(kind, share)
    total += share
  }
  if (total !== pool) {
    throw new Error(
      `the ID allocation spends ${total} of ${pool} ID results; it has to spend them all`,
    )
  }
  return spent
}
