/**
 * The eighteen spells Treefolk and Firewalkers can cast, from `data/spells.json`.
 *
 * Hand-authored content, like `presets.json` and unlike `data/starter/` -- no
 * importer writes it. Validated eagerly here for the same reason the die data is: a
 * malformed spell should fail loudly at load rather than produce a wrong game.
 *
 * **A spell may carry neither `effect` nor `handler`**, which means transcribed but
 * not implemented. `resolvesSpell` answers false for it and `castableSpells` never
 * offers it -- the same deliberate silence `sai: 'results'` gives an SAI it does not
 * know, and for the same reason: it is what makes a half-built rung playable rather
 * than a rung that throws. The state is temporary and `spells.test.ts` is where the
 * list of who is still in it lives.
 */
import rawSpells from '../../data/spells.json'

import { DataError, type Element, type ResultType } from './types'

/**
 * A spell's element. Not `Element`: `elemental` is a spell property (castable with
 * magic of any *one* element) and never a colour a die or a terrain carries, and
 * `ivory` is the reverse.
 */
export type SpellElement = Element | 'elemental'

/**
 * What the caster names when announcing.
 *
 * The rules give five target kinds -- army, unit(s), terrain, DUA, BUA -- and this
 * splits them by whose they may be, because "target any opposing army" and "target
 * any army" are different questions to put to a player.
 *
 * `own_army` is a house rule (v1 Phase 9a, `RULES-V0.md` section 15): a beneficial
 * army spell reaches only the caster's own armies. The rules let a Stone Skin land on
 * an enemy army, which only ever matters with more than two players. `army` stays in
 * the vocabulary because it is what the rulebook says; no spell in this box uses it.
 *
 * `own_dua` is units in your DUA (Resurrect Dead: one health-worth per casting);
 * `dua` is the area itself (Accelerated Growth: "target your DUA").
 */
export type SpellTargetKind =
  | 'army'
  | 'own_army'
  | 'opposing_army'
  | 'own_unit'
  | 'opposing_unit'
  | 'units'
  | 'terrain'
  | 'own_dua'
  | 'dua'

/** Who a declarative spell's modifiers reach. The last three are terrain-scoped. */
export type SpellScope = 'army' | 'unit' | 'all_armies' | 'attackers' | 'maneuverers'

/** A modifier as the data spells it, before `*` is expanded. */
export interface SpellModifierSpec {
  readonly kind: 'add' | 'subtract' | 'divide' | 'multiply' | 'ignore_ids'
  /** `'*'` means every result type -- Ash Storm, and nothing else so far. */
  readonly resultType: ResultType | '*'
  readonly amount?: number
  readonly by?: number
  readonly share?: 'all' | 'id'
}

/** A spell that is modifiers on a target for a duration, and nothing more. */
export interface SpellEffectSpec {
  readonly scope: SpellScope
  readonly modifiers: readonly SpellModifierSpec[]
  /** Every spell in scope that lasts at all lasts until the caster's next turn. */
  readonly duration: 'caster_next_turn'
}

export interface Spell {
  readonly id: string
  readonly name: string
  readonly element: SpellElement
  readonly cost: number
  /** `'any'`, or a species id: "a species spell may only be cast with results
   *  generated by units from that species". */
  readonly species: string
  readonly target: SpellTargetKind
  /**
   * Combined castings multiply one highlighted number. The rulebook encodes this as
   * red text, which no extraction preserves, so it is transcribed by eye.
   */
  readonly cumulative: boolean
  /** The `R` column: castable by an army in the Reserve Area. */
  readonly reserves: boolean
  /** The `C` column: castable with magic the Cantrip SAI generated outside a magic
   *  action. */
  readonly cantrip: boolean
  /** The rules text, verbatim. Both clients render this; there is no second copy. */
  readonly text: string
  /** Declarative spells only. Mutually exclusive with `handler`; both may be absent. */
  readonly effect?: SpellEffectSpec
  /** Names a function in `engine/spells.ts`: a spell that does something at
   *  resolution time that is not an `Effect`. */
  readonly handler?: string
}

const SPELL_ELEMENTS: readonly string[] = ['air', 'water', 'earth', 'fire', 'death', 'elemental']
const SPELL_TARGETS: readonly string[] = [
  'army',
  'own_army',
  'opposing_army',
  'own_unit',
  'opposing_unit',
  'units',
  'terrain',
  'own_dua',
  'dua',
]
const SPELL_SCOPES: readonly string[] = ['army', 'unit', 'all_armies', 'attackers', 'maneuverers']
const MODIFIER_KINDS: readonly string[] = ['add', 'subtract', 'divide', 'multiply', 'ignore_ids']
const RESULT_TYPES: readonly string[] = ['melee', 'missile', 'magic', 'save', 'maneuver', '*']

function oneOf<T extends string>(
  value: string,
  allowed: readonly string[],
  label: string,
  context: string,
): T {
  if (!allowed.includes(value)) {
    throw new DataError(`${context}: unknown ${label} ${JSON.stringify(value)}`)
  }
  return value as T
}

function loadEffect(raw: unknown, context: string): SpellEffectSpec {
  const effect = raw as {
    scope: string
    modifiers: readonly { kind: string; resultType: string; amount?: number; by?: number; share?: string }[]
    duration: string
  }

  if (effect.duration !== 'caster_next_turn') {
    throw new DataError(`${context}: unknown duration ${JSON.stringify(effect.duration)}`)
  }
  if (effect.modifiers.length === 0) {
    throw new DataError(`${context}: effect with no modifiers`)
  }

  const modifiers = effect.modifiers.map((m): SpellModifierSpec => ({
    kind: oneOf<SpellModifierSpec['kind']>(m.kind, MODIFIER_KINDS, 'modifier kind', context),
    resultType: oneOf<ResultType | '*'>(m.resultType, RESULT_TYPES, 'result type', context),
    ...(m.amount === undefined ? {} : { amount: m.amount }),
    ...(m.by === undefined ? {} : { by: m.by }),
    ...(m.share === undefined ? {} : { share: m.share as 'all' | 'id' }),
  }))

  return {
    scope: oneOf<SpellScope>(effect.scope, SPELL_SCOPES, 'scope', context),
    modifiers,
    duration: 'caster_next_turn',
  }
}

function load(): readonly Spell[] {
  const seen = new Set<string>()

  return rawSpells.spells.map((s): Spell => {
    const context = `spell ${s.id}`

    if (seen.has(s.id)) throw new DataError(`${context}: duplicate id`)
    seen.add(s.id)

    if (!Number.isInteger(s.cost) || s.cost < 1) {
      throw new DataError(`${context}: cost ${s.cost} is not a positive integer`)
    }
    if (s.text.trim() === '') throw new DataError(`${context}: empty rules text`)

    const raw = s as typeof s & { effect?: unknown; handler?: string }
    if (raw.effect !== undefined && raw.handler !== undefined) {
      throw new DataError(`${context}: has both an effect and a handler`)
    }

    return {
      id: s.id,
      name: s.name,
      element: oneOf<SpellElement>(s.element, SPELL_ELEMENTS, 'element', context),
      cost: s.cost,
      species: s.species,
      target: oneOf<SpellTargetKind>(s.target, SPELL_TARGETS, 'target', context),
      cumulative: s.cumulative,
      reserves: s.reserves,
      cantrip: s.cantrip,
      text: s.text,
      ...(raw.effect === undefined ? {} : { effect: loadEffect(raw.effect, context) }),
      ...(raw.handler === undefined ? {} : { handler: raw.handler }),
    }
  })
}

export const SPELLS: readonly Spell[] = load()

const byId = new Map(SPELLS.map((s) => [s.id, s]))

export function spell(id: string): Spell {
  const found = byId.get(id)
  if (!found) throw new DataError(`no such spell: ${id}`)
  return found
}

/** Whether this spell's element requirement is satisfiable by magic of `element`.
 *  An Elemental spell takes any single element; every other spell takes its own. */
export function spellAcceptsElement(s: Spell, element: Element): boolean {
  return s.element === 'elemental' ? true : s.element === element
}

/** Whether a caster of this species may cast this spell at all. */
export function spellAllowsSpecies(s: Spell, speciesId: string): boolean {
  return s.species === 'any' || s.species === speciesId
}
